### ISSUE TITLE
Class template type argument requirements are undocumented

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/cpp-docs#963]
The documentation currently doesn't state any requirements imposed by the implementation of `concurrency::task` on its template type argument. I recently ran into issues when using a type that was moveable, but not copyable.

Could you please add documentation on the requirements (default-constructible, copy-constructible, copy-assignable, move-constructible, move-assignable, swappable, etc.).

On an unrelated note, I cannot make out, why the "Syntax" section contains

    template <typename T>
    class task;

as well as

    template<typename _ReturnType>
    class task;

With the exception of the type template parameter name, they appear to be the same. Although both type parameters are documented, I don't think that the explanation for `T` is correct. What's up with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2dd4014-f009-dd9c-3d39-5de0897871dd
* Version Independent ID: 10782062-6be2-8aff-1d87-9e8430f69234
* Content: [task Class (Concurrency Runtime)](https://docs.microsoft.com/en-us/cpp/parallel/concrt/reference/task-class?view=vs-2019#feedback)
* Content Source: [docs/parallel/concrt/reference/task-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/parallel/concrt/reference/task-class.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@tim-weis thanks for the feedback! I have fixed the syntax block which was incorrect as you found. As for the requirements or assumptions on the type parameter, was your problem at compile time or run-time? I can run a task that has a result type with a deleted copy constructor and copy assignment operator. I did add a note (taken from pppltasks.h) to the effect that a task class behaves like a shared_ptr.

**Comment by tim-weis** [comment]
I ran into compile-time errors, though I do not recall the specifics. Luckily, Raymond Chen [did](https://devblogs.microsoft.com/oldnewthing/20200812-00/?p=104075). The blog entry makes 2 good points: It explains the constraints (still missing from the *official* documentation) and why they exist. And it makes a suggestion on how to get better compiler diagnostics.
